name: "Build Hub"

on:
  push:
    branches:
      - main

jobs:
  Build-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Hub"
        uses: smellofair/rules-actions/build-hub@v0.3
        with:
          pat: ${{ secrets.PAT }}
