name: "Build Hub"

on:
  push:
    branches:
      - main

jobs:
  Build-Hub:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: "Build Hub"
        uses: smellofair/rules-actions/build-hub@v0.3
        with:
          pat: ${{ secrets.PAT }}
