name: "Update Hub"

on:
  repository_dispatch:
    types: ["update-hub"]

jobs:
  Update-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: "Update Hub"
        uses: cephalofair/rules-actions/update-hub@v0.3
        with:
          source: ${{ github.event.client_payload.source }}
          pat: ${{ secrets.PAT }}
